"""users table

Revision ID: 914a902191cd
Revises: 
Create Date: 2019-12-12 09:24:29.533999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914a902191cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=256), nullable=True),
    sa.Column('output', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_record_data'), 'query_record', ['data'], unique=False)
    op.create_index(op.f('ix_query_record_output'), 'query_record', ['output'], unique=False)
    op.create_index(op.f('ix_query_record_user_id'), 'query_record', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('twofa', sa.String(length=11), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('inputtext', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_twofa'), 'user', ['twofa'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_twofa'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_query_record_user_id'), table_name='query_record')
    op.drop_index(op.f('ix_query_record_output'), table_name='query_record')
    op.drop_index(op.f('ix_query_record_data'), table_name='query_record')
    op.drop_table('query_record')
    # ### end Alembic commands ###
